SubjectSelection/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SubjectSelection.Models
{
    public class Subject
    {
        public int SubjectId { get; set; }

        public int ParentListId { get; set; }
        public SubjectList ParentList { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public ICollection<Group> Groups { get; set; }
        public ICollection<UserEditableSubjects> UsersWhoCanEdit { get; set; }
    }
}

SubjectSelection/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SubjectSelection.Models;

namespace SubjectSelection.Controllers
{
    public class GroupsController : Controller
    {
        private readonly UserManager<User> _userManager;

        private readonly SubjectSelectionDbContext _context;

        public GroupsController(UserManager<User> userManager, SubjectSelectionDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Groups
        public async Task<IActionResult> Index(int parentSubjectId)
        {
            var parentSubject = await _context.Subjects
                .Include(s => s.ParentList)
                .ThenInclude(sl => sl.UsersWhoCanEdit)
                .ThenInclude(uel => uel.User)
                .Include(s => s.Groups)
                .FirstAsync(s => s.SubjectId == parentSubjectId);

            ViewBag.parentSubjectName = parentSubject.Name;
            ViewBag.parentSubjectId = parentSubjectId;

            var usersWhoCanEdit = parentSubject.ParentList.UsersWhoCanEdit
                .Where(uel => uel.SubjectListId == parentSubject.ParentList.SubjectListId)
                .Select(uel => uel.User)
                .Select(u => u.Id)
                .ToList();

            usersWhoCanEdit.AddRange(usersWhoCanEdit);

            usersWhoCanEdit.Insert(0, parentSubject.ParentList.OwnerId);

            ViewBag.usersWhoCanEdit = usersWhoCanEdit;            

            var currentUser = await this.GetCurrentUserAsync();
            ViewBag.currentUserId = currentUser.Id;


            return View(parentSubject.Groups);
        }

        // GET: Groups/CreateSubject
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGroup(string groupName, int groupCapacity, int parentSubjectId)
        {
            var parentSubject = await _context.Subjects.FirstOrDefaultAsync(s => s.SubjectId == parentSubjectId);

            var group = new Group()
            {
                Name = groupName,
                SubjectId = parentSubjectId,
                Subject = parentSubject,
                Capacity = groupCapacity
            };

            if (ModelState.IsValid)
            {
                _context.Add(group);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { parentSubjectId = parentSubjectId });
            }

            //TODO
            //Jak model invalid
            return View();
        }

        public async Task<IActionResult> Join(int groupId, int parentSubjectId)
        {
            var currentUser = await this.GetCurrentUserAsync();

            var parentList = (await _context.Subjects
                .Include(s => s.ParentList)
                .ThenInclude(sl => sl.ExclusiveSubjectListsA)
                .Include(s => s.ParentList)
                .ThenInclude(sl => sl.ExclusiveSubjectListsB)
                .FirstOrDefaultAsync(s => s.SubjectId == parentSubjectId)).ParentList;

            var exclusiveSubjectListsIds = parentList.ExclusiveSubjectListsA.Select(esl => esl.SubjectListBId)?.ToList();
            exclusiveSubjectListsIds.AddRange(parentList.ExclusiveSubjectListsB.Select(esl => esl.SubjectListAId));

            var exclusiveSubjectLists = _context.SubjectLists
                .Include(sl => sl.Subjects)
                .ThenInclude(s => s.Groups)
                .ThenInclude(g => g.UsersInGroup)
                .Where(sl => exclusiveSubjectListsIds.Contains(sl.SubjectListId) && sl.Subjects.Where(s => s.Groups.Where(g => g.UsersInGroup.Where(uig => uig.UserId == currentUser.Id).Select(uig => uig.GroupId).Contains(g.GroupId)).Select(g => g.SubjectId).Contains(s.SubjectId)).Select(s => s.ParentListId).Contains(sl.SubjectListId));

            if (!exclusiveSubjectLists.Any())
            {
                var userGroup = await _context.UserGroups?.FirstOrDefaultAsync(ug => ug.GroupId == groupId && ug.UserId == currentUser.Id);
                if (userGroup == null)
                {
                    var newUserGroup = new UserGroups()
                    {
                        GroupId = groupId,
                        UserId = currentUser.Id,
                        User = currentUser
                    };

                    if (ModelState.IsValid)
                    {
                        _context.Add(newUserGroup);
                        await _context.SaveChangesAsync();
                        return RedirectToAction("Index", new { parentSubjectId = parentSubjectId });
                    }
                }
                else
                    return RedirectToAction("Index", new { parentSubjectId = parentSubjectId });
            }


            //TODO
            //Tutaj wchodzi jak ModelState invalid, zmienic
            //return View();
            return RedirectToAction(nameof(Error));
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }






        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = await _context.Groups
                .Include(g => g.UsersInGroup)
                .SingleOrDefaultAsync(m => m.GroupId == id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId");
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupId,Capacity,SubjectId,Name,ClassDate")] Group @group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId", @group.SubjectId);
            return View(@group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups.SingleOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId", @group.SubjectId);
            return View(@group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GroupId,Capacity,SubjectId,Name,ClassDate")] Group group)
        {
            if (id != group.GroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(group.GroupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { parentSubjectId = group.SubjectId });
            }
            //ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId", group.SubjectId);
            return View(group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = await _context.Groups
                .Include(g => g.Subject)
                .SingleOrDefaultAsync(m => m.GroupId == id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var group = await _context.Groups.SingleOrDefaultAsync(m => m.GroupId == id);
            _context.Groups.Remove(group);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { parentSubjectId = group.SubjectId });
        }

        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.GroupId == id);
        }
    }
}

SubjectSelection/ViewComponents/ExclusiveListsViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SubjectSelection.Models;
using System.Linq;
using System.Threading.Tasks;

namespace SubjectSelection.ViewComponents
{
    public class ExclusiveListsViewComponent : ViewComponent
    {
        private readonly SubjectSelectionDbContext _context;

        private readonly UserManager<User> _userManager;

        public ExclusiveListsViewComponent(UserManager<User> userManager, SubjectSelectionDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IViewComponentResult> InvokeAsync(int parentListId)
        {
            var user = await this.GetCurrentUserAsync();
            ViewBag.currentUserId = user.Id;

            var parentSubjectList = await _context.SubjectLists.Include(sl => sl.ExclusiveSubjectListsA).Include(sl => sl.ExclusiveSubjectListsB).FirstOrDefaultAsync(sl => sl.SubjectListId == parentListId);
            ViewBag.parentList = parentSubjectList;

            var exclusiveLists = parentSubjectList.ExclusiveSubjectListsA.Select(esl => esl.SubjectListBId).ToList();
            exclusiveLists.AddRange(parentSubjectList.ExclusiveSubjectListsB.Select(esl => esl.SubjectListAId));

            var subjectLists = _context.SubjectLists.Where(sl => exclusiveLists.Contains(sl.SubjectListId));

            return View(subjectLists);
        }
    }
}

SubjectSelection/ViewComponents/UsersWhoCaneditViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SubjectSelection.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SubjectSelection.ViewComponents
{
    public class UsersWhoCanEditViewComponent : ViewComponent
    {
        private readonly SubjectSelectionDbContext _context;

        private readonly UserManager<User> _userManager;

        public UsersWhoCanEditViewComponent(UserManager<User> userManager, SubjectSelectionDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IViewComponentResult> InvokeAsync(int parentListId)
        {
            var user = await this.GetCurrentUserAsync();
            ViewBag.currentUserId = user.Id;

            var subjectList = await _context.SubjectLists
                .Include(sl => sl.UsersWhoCanEdit)
                    .ThenInclude(uel => uel.User)//x => x. //.Select(uel => uel.User))
                .Include(sl => sl.Owner)
                .FirstOrDefaultAsync(sl => sl.SubjectListId == parentListId);

            var usersWhoCanEdit = subjectList.UsersWhoCanEdit
                .Where(uel => uel.SubjectListId == parentListId)
                .Select(uel => uel.User)
                .ToList();

            usersWhoCanEdit.Insert(0, subjectList.Owner);

            ViewBag.parentList = subjectList;

            return View(usersWhoCanEdit);
        }
    }
}

SubjectSelection/Views/Subjects/Create.cshtml
@model SubjectSelection.Models.Subject

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Subject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ParentListId" class="control-label"></label>
                <select asp-for="ParentListId" class ="form-control" asp-items="ViewBag.ParentListId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SubjectSelection/Views/Subjects/Delete.cshtml
@model SubjectSelection.Models.Subject

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ParentList)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ParentList.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SubjectId" />
        <input type="submit" value="Delete" asp-route-parentListId="@Model.ParentListId" class="btn btn-default" /> |
        <a asp-action="Index" asp-route-parentListId="@Model.ParentListId">Back to List</a>
    </form>
</div>

SubjectSelection/Views/Subjects/Details.cshtml
@model SubjectSelection.Models.Subject

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ParentList)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ParentList.SubjectListId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SubjectId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SubjectSelection/Views/Subjects/Edit.cshtml
@model SubjectSelection.Models.Subject

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Subject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SubjectId" />
            <input type="hidden" asp-for="ParentListId" />
            @*<div class="form-group">
            <label asp-for="ParentListId" class="control-label"></label>
            <select asp-for="ParentListId" class="form-control" asp-items="ViewBag.ParentListId"></select>
            <span asp-validation-for="ParentListId" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-parentListId="@Model.ParentListId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SubjectSelection/Views/Subjects/Index.cshtml
@model IEnumerable<SubjectSelection.Models.Subject>

@{
    ViewData["Title"] = ViewBag.parentListName;//"Index";
    var parentList = ViewBag.parentList;
    var currentUserId = ViewBag.currentUserId;
    List<int> usersWhoCanEdit = ViewBag.usersWhoCanEdit;
}

<h2>@ViewBag.parentListName</h2>

@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@

@*<div class="row">
        <div class="col-md-12">
            <form asp-action="CreateSubject" asp-route-parentListId="@parentListId">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="subjectName">Subject Name</label>
                        </div>
                        <div class="col-md-6">
                            <label for="subjectDescription">Subject Description</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="subjectName" placeholder="Enter name" name="subjectName" />
                        </div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-11">
                                    <input type="text" class="form-control" id="subjectDescription" placeholder="Enter description" name="subjectDescription" />
                                </div>
                                <div class="col-md-1">
                                    <button type="submit" class="btn btn-primary">Create</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>*@
<div class="row">
    <div class="col-md-6">
        <div class="@(usersWhoCanEdit.Contains(currentUserId) ? string.Empty : "hidden") row">
            <div class="col-md-12">
                <form asp-action="CreateSubject" asp-route-parentListId="@parentList.SubjectListId">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4">
                                <label for="subjectName">Subject Name</label>
                            </div>
                            <div class="col-md-6">
                                <label for="subjectDescription">Subject Description</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <input type="text" class="form-control" id="subjectName" placeholder="Enter name" name="subjectName" />
                            </div>
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" id="subjectDescription" placeholder="Enter description" name="subjectDescription" />
                                    </div>
                                    <div class="col-md-3">
                                        <button type="submit" class="btn btn-primary">Create</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                Subjects:
                <table class="table" style="table-layout: fixed;">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ParentList)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr style="word-wrap: break-word">
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td >
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ParentList.Name)
                            </td>
                            <td class="@(usersWhoCanEdit.Contains(currentUserId)? string.Empty : "hidden")">
                                <a asp-controller="Groups" asp-action="Index" asp-route-parentSubjectId="@item.SubjectId">Details</a> |
                                <a asp-action="Edit" asp-route-id="@item.SubjectId">Edit</a> |
                                <a asp-action="Delete" asp-route-id="@item.SubjectId">Delete</a>
                            </td>
                            <td class="@(!usersWhoCanEdit.Contains(currentUserId) ? string.Empty : "hidden")">
                                <a asp-controller="Groups" asp-action="Index" asp-route-parentSubjectId="@item.SubjectId">Details</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                @await Component.InvokeAsync("UsersWhoCanEdit", new { parentListId = parentList.SubjectListId })
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                Exclusive lists:
                @await Component.InvokeAsync("ExclusiveLists", new { parentListId = parentList.SubjectListId })
                <div class="@(currentUserId == parentList.OwnerId ? string.Empty : "hidden")">
                    <form asp-action="AddExlusiveList" asp-route-parentListId="@parentList.SubjectListId">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-11">
                                    @Html.DropDownList("subjectListId", ViewBag.subjectLists as SelectList, new { @class = "form-control" })
                                </div>
                                <div class="col-md-1">
                                    <button type="submit" class="btn btn-primary">Add</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@*<div class="row">
        <div class="col-md-12">
            @await Component.InvokeAsync("ExclusiveLists", new { parentListId = parentListId })
            <form asp-action="AddExlusiveList" asp-route-parentListId="@parentListId">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            @Html.DropDownList("subjectListId", ViewBag.subjectLists as SelectList, new { @class = "form-control" })
                        </div>
                        <div class="col-md-1">
                            <button type="submit" class="btn btn-primary">Add</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>*@