SubjectSelection/Models/Group.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SubjectSelection.Models
{
    public class Group // Sekcja
    {
        public int GroupId { get; set; }
        public int Capacity { get; set; }

        public int SubjectId { get; set; }
        public Subject Subject { get; set; }

        public string Name { get; set; }
        public string ClassDate { get; set; } //Dzień i godzina zajęć

        public ICollection<UserGroups> UsersInGroup { get; set; }
    }
}

SubjectSelection/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SubjectSelection.Models;

namespace SubjectSelection.Controllers
{
    public class GroupsController : Controller
    {
        private readonly UserManager<User> _userManager;

        private readonly SubjectSelectionDbContext _context;

        public GroupsController(UserManager<User> userManager, SubjectSelectionDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Groups
        public async Task<IActionResult> Index(int parentSubjectId)
        {
            var parentSubject = await _context.Subjects
                .Include(s => s.ParentList)
                .ThenInclude(sl => sl.UsersWhoCanEdit)
                .ThenInclude(uel => uel.User)
                .Include(s => s.Groups)
                .FirstAsync(s => s.SubjectId == parentSubjectId);

            ViewBag.parentSubjectName = parentSubject.Name;
            ViewBag.parentSubjectId = parentSubjectId;

            var usersWhoCanEdit = parentSubject.ParentList.UsersWhoCanEdit
                .Where(uel => uel.SubjectListId == parentSubject.ParentList.SubjectListId)
                .Select(uel => uel.User)
                .Select(u => u.Id)
                .ToList();

            usersWhoCanEdit.AddRange(usersWhoCanEdit);

            usersWhoCanEdit.Insert(0, parentSubject.ParentList.OwnerId);

            ViewBag.usersWhoCanEdit = usersWhoCanEdit;            

            var currentUser = await this.GetCurrentUserAsync();
            ViewBag.currentUserId = currentUser.Id;


            return View(parentSubject.Groups);
        }

        // GET: Groups/CreateSubject
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGroup(string groupName, int groupCapacity, int parentSubjectId)
        {
            var parentSubject = await _context.Subjects.FirstOrDefaultAsync(s => s.SubjectId == parentSubjectId);

            var group = new Group()
            {
                Name = groupName,
                SubjectId = parentSubjectId,
                Subject = parentSubject,
                Capacity = groupCapacity
            };

            if (ModelState.IsValid)
            {
                _context.Add(group);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { parentSubjectId = parentSubjectId });
            }

            //TODO
            //Jak model invalid
            return View();
        }

        public async Task<IActionResult> Join(int groupId, int parentSubjectId)
        {
            var currentUser = await this.GetCurrentUserAsync();

            var parentList = (await _context.Subjects
                .Include(s => s.ParentList)
                .ThenInclude(sl => sl.ExclusiveSubjectListsA)
                .Include(s => s.ParentList)
                .ThenInclude(sl => sl.ExclusiveSubjectListsB)
                .FirstOrDefaultAsync(s => s.SubjectId == parentSubjectId)).ParentList;

            var exclusiveSubjectListsIds = parentList.ExclusiveSubjectListsA.Select(esl => esl.SubjectListBId)?.ToList();
            exclusiveSubjectListsIds.AddRange(parentList.ExclusiveSubjectListsB.Select(esl => esl.SubjectListAId));

            var exclusiveSubjectLists = _context.SubjectLists
                .Include(sl => sl.Subjects)
                .ThenInclude(s => s.Groups)
                .ThenInclude(g => g.UsersInGroup)
                .Where(sl => exclusiveSubjectListsIds.Contains(sl.SubjectListId) && sl.Subjects.Where(s => s.Groups.Where(g => g.UsersInGroup.Where(uig => uig.UserId == currentUser.Id).Select(uig => uig.GroupId).Contains(g.GroupId)).Select(g => g.SubjectId).Contains(s.SubjectId)).Select(s => s.ParentListId).Contains(sl.SubjectListId));

            if (!exclusiveSubjectLists.Any())
            {
                var userGroup = await _context.UserGroups?.FirstOrDefaultAsync(ug => ug.GroupId == groupId && ug.UserId == currentUser.Id);
                if (userGroup == null)
                {
                    var newUserGroup = new UserGroups()
                    {
                        GroupId = groupId,
                        UserId = currentUser.Id,
                        User = currentUser
                    };

                    if (ModelState.IsValid)
                    {
                        _context.Add(newUserGroup);
                        await _context.SaveChangesAsync();
                        return RedirectToAction("Index", new { parentSubjectId = parentSubjectId });
                    }
                }
                else
                    return RedirectToAction("Index", new { parentSubjectId = parentSubjectId });
            }


            //TODO
            //Tutaj wchodzi jak ModelState invalid, zmienic
            //return View();
            return RedirectToAction(nameof(Error));
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }






        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = await _context.Groups
                .Include(g => g.UsersInGroup)
                .SingleOrDefaultAsync(m => m.GroupId == id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId");
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupId,Capacity,SubjectId,Name,ClassDate")] Group @group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId", @group.SubjectId);
            return View(@group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups.SingleOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId", @group.SubjectId);
            return View(@group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GroupId,Capacity,SubjectId,Name,ClassDate")] Group group)
        {
            if (id != group.GroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(group.GroupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { parentSubjectId = group.SubjectId });
            }
            //ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId", group.SubjectId);
            return View(group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = await _context.Groups
                .Include(g => g.Subject)
                .SingleOrDefaultAsync(m => m.GroupId == id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var group = await _context.Groups.SingleOrDefaultAsync(m => m.GroupId == id);
            _context.Groups.Remove(group);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { parentSubjectId = group.SubjectId });
        }

        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.GroupId == id);
        }
    }
}

SubjectSelection/ViewComponents/UsersInGroupViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SubjectSelection.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SubjectSelection.ViewComponents
{
    public class UsersInGroupViewComponent : ViewComponent
    {
        private readonly SubjectSelectionDbContext _context;
        private readonly UserManager<User> _userManager;

        public UsersInGroupViewComponent(UserManager<User> userManager, SubjectSelectionDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IViewComponentResult> InvokeAsync(int groupId)
        {
            var user = await this.GetCurrentUserAsync();

            var group = await _context.Groups
                .Include(g => g.Subject)
                .FirstOrDefaultAsync(g => g.GroupId == groupId);

            var parentListId = group.Subject.ParentListId;

            var parentList = await _context.SubjectLists
                .Include(sl => sl.UsersWhoCanEdit)
                .ThenInclude(uel => uel.User)
                .FirstOrDefaultAsync(sl => sl.SubjectListId == parentListId);

            var usersWhoCanEdit = parentList.UsersWhoCanEdit
                .Where(uel => uel.SubjectListId == parentList.SubjectListId)
                .Select(uel => uel.User)
                .Select(u => u.Id)
                .ToList();

            usersWhoCanEdit.AddRange(usersWhoCanEdit);

            usersWhoCanEdit.Insert(0, parentList.OwnerId);

            ViewBag.usersWhoCanEdit = usersWhoCanEdit;
            ViewBag.currentUserId = user.Id;

            var usersInGroupIds = _context.UserGroups.Where(ug => ug.GroupId == groupId).Select(ug => ug.UserId);
            var usersInGroup = _context.Users.Where(u => usersInGroupIds.Contains(u.Id));

            return View(usersInGroup);
        }
    }
}

SubjectSelection/Views/Groups/Create.cshtml
@model SubjectSelection.Models.Group

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class ="form-control" asp-items="ViewBag.SubjectId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassDate" class="control-label"></label>
                <input asp-for="ClassDate" class="form-control" />
                <span asp-validation-for="ClassDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SubjectSelection/Views/Groups/Delete.cshtml
@model SubjectSelection.Models.Group

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ClassDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClassDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subject.SubjectId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GroupId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index" asp-route-parentSubjectId="@Model.SubjectId">Back to List</a>
    </form>
</div>

SubjectSelection/Views/Groups/Details.cshtml
@model SubjectSelection.Models.Group

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ClassDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClassDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subject.SubjectId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GroupId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SubjectSelection/Views/Groups/Edit.cshtml
@model SubjectSelection.Models.Group

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GroupId" />
            <input type="hidden" asp-for="SubjectId" />

            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="SubjectId" class="control-label"></label>
            <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId"></select>
            <span asp-validation-for="SubjectId" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassDate" class="control-label"></label>
                <input asp-for="ClassDate" class="form-control" />
                <span asp-validation-for="ClassDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SubjectSelection/Views/Groups/Index.cshtml
@model IEnumerable<SubjectSelection.Models.Group>
@{
    ViewData["Title"] = "Index";
    var parentSubjectName = ViewBag.parentSubjectName;
    var parentSubjectId = ViewBag.parentSubjectId;
    var usersWhoCanEdit = ViewBag.usersWhoCanEdit;
    var currentUserId = ViewBag.currentUserId;
}

<h2>@ViewBag.parentSubjectName</h2>

<form asp-action="CreateGroup" asp-route-parentSubjectId="@ViewBag.parentSubjectId" class="@(usersWhoCanEdit.Contains(currentUserId) ? string.Empty : "hidden")">
    <div class="form-group">
        <div class="row">
            <div class="col-md-6">
                <label for="groupName">Group Name</label>
            </div>
            <div class="col-md-6">
                <label for="groupCapacity">Group capacity</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <input type="text" class="form-control" id="groupName" placeholder="Enter name" name="groupName" />
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-11">
                        <input type="number" class="form-control" id="groupCapacity" placeholder="Enter group capacity" name="groupCapacity" />
                    </div>
                    <div class="col-md-1">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Description
                @*@Html.DisplayNameFor(model => model.ClassDate)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Capacity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClassDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject.SubjectId)
                </td>
                <td>
                    <a asp-action="Join" asp-route-groupId="@item.GroupId" asp-route-parentSubjectId="@ViewBag.parentSubjectId">Join</a> 
                    <span class="@(usersWhoCanEdit.Contains(currentUserId) ? string.Empty : "hidden")">
                        |
                        <a asp-action="Edit" asp-route-id="@item.GroupId">Edit</a> |
                        <a asp-action="Delete" asp-route-id="@item.GroupId">Delete</a>
                    </span>
                    
                </td>
            </tr>
            <tr>
                @await Component.InvokeAsync("UsersInGroup", new { groupId = item.GroupId })
            </tr>
        }
    </tbody>
</table>