SubjectSelection/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SubjectSelection.Models;

namespace SubjectSelection.Controllers
{
    [Authorize]
    public class SubjectsController : Controller
    {

        private readonly UserManager<User> _userManager;

        private readonly SubjectSelectionDbContext _context;

        public SubjectsController(SubjectSelectionDbContext context, UserManager<User> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Subjects
        public async Task<IActionResult> Index(int parentListId)
        {
            try
            {
                var user = await this.GetCurrentUserAsync();
                ViewBag.currentUserId = user.Id;

                var parentList = await _context.SubjectLists
                    .Include(sl => sl.Subjects)
                    .Include(sl => sl.UsersWhoCanEdit)
                    .ThenInclude(uel => uel.User)
                    .FirstAsync(sl => sl.SubjectListId == parentListId);

                ViewBag.parentListName = parentList.Name;
                ViewBag.parentList = parentList;

                var usersWhoCanEdit = parentList.UsersWhoCanEdit
                .Where(uel => uel.SubjectListId == parentListId)
                .Select(uel => uel.User)
                .Select(u => u.Id)
                .ToList();

                usersWhoCanEdit.AddRange(usersWhoCanEdit);

                usersWhoCanEdit.Insert(0, parentList.OwnerId);

                ViewBag.usersWhoCanEdit = usersWhoCanEdit;//user.Id;


                //SubjectLists do dropdownu
                var subjectLists = _context.SubjectLists.Where(sl => sl.OwnerId == parentList.OwnerId && sl.SubjectListId != parentListId);
                ViewBag.subjectLists = new SelectList(subjectLists, "SubjectListId", "Name");

                return View(parentList.Subjects);
            }
            catch (InvalidOperationException ex)
            {
                return RedirectToAction(nameof(Error));
            }
        }


        // GET: Subjects/CreateSubject
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSubject(string subjectName, string subjectDescription, int parentListId)
        {
            var user = await this.GetCurrentUserAsync();

            var parentList = await _context.SubjectLists.FirstOrDefaultAsync(sl => sl.SubjectListId == parentListId);

            if (parentList.OwnerId == user.Id)
            {
                var subject = new Subject()
                {
                    Name = subjectName,
                    Description = subjectDescription,
                    ParentListId = parentListId,
                    ParentList = parentList
                };

                if (ModelState.IsValid)
                {
                    _context.Add(subject);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", new { parentListId = parentListId });
                }
            }


            //TODO
            //Jak model invalid
            //return View();
            return RedirectToAction("Index", new { parentListId = parentListId });
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(int userId, int parentListId)
        {
            try
            {
                var user = await this.GetCurrentUserAsync();
                var subjectList = await _context.SubjectLists.FirstOrDefaultAsync(sl => sl.SubjectListId == parentListId);

                if (subjectList.OwnerId == user.Id)
                {
                    var userEditableList = new UserEditableLists()
                    {
                        SubjectListId = parentListId,
                        UserId = userId
                    };

                    if (ModelState.IsValid)
                    {
                        _context.Add(userEditableList);
                        await _context.SaveChangesAsync();
                        return RedirectToAction("Index", new { parentListId = parentListId });
                    }
                }
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction(nameof(Error));
            }
            return RedirectToAction(nameof(Error));
        }

        public async Task<IActionResult> AddExlusiveList(int subjectListId, int parentListId)
        {
            var user = await this.GetCurrentUserAsync();
            var parentList = await _context.SubjectLists.FirstOrDefaultAsync(sl => sl.SubjectListId == parentListId);
            if (parentList.OwnerId == user.Id)
            {
                var exclusiveList = new ExclusiveSubjectLists()
                {
                    SubjectListAId = parentListId,
                    SubjectListBId = subjectListId
                };

                if (ModelState.IsValid)
                {
                    _context.Add(exclusiveList);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", new { parentListId = parentListId });
                }
            }

            return RedirectToAction(nameof(Error));
        }

        public async Task<IActionResult> DeleteExclusiveList(int subjectListId, int parentListId)
        {
            var user = await this.GetCurrentUserAsync();
            var parentList = await _context.SubjectLists.FirstOrDefaultAsync(sl => sl.SubjectListId == parentListId);

            if (parentList.OwnerId == user.Id)
            {
                var exclusiveSubjectList = await _context.ExclusiveSubjectLists.FirstOrDefaultAsync(esl => (esl.SubjectListAId == subjectListId && esl.SubjectListBId == parentListId) || (esl.SubjectListAId == parentListId && esl.SubjectListBId == subjectListId));

                if (ModelState.IsValid)
                {
                    _context.Remove(exclusiveSubjectList);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", new { parentListId = parentListId });
                }
            }

            return RedirectToAction(nameof(Error));
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }





        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .Include(s => s.ParentList)
                .SingleOrDefaultAsync(m => m.SubjectId == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
            ViewData["ParentListId"] = new SelectList(_context.SubjectLists, "SubjectListId", "SubjectListId");
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubjectId,ParentListId,Name,Description")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentListId"] = new SelectList(_context.SubjectLists, "SubjectListId", "SubjectListId", subject.ParentListId);
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.SingleOrDefaultAsync(m => m.SubjectId == id);
            if (subject == null)
            {
                return NotFound();
            }
            ViewData["ParentListId"] = new SelectList(_context.SubjectLists, "SubjectListId", "SubjectListId", subject.ParentListId);
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SubjectId,ParentListId,Name,Description")] Subject subject)
        {
            if (id != subject.SubjectId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.SubjectId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));

SubjectSelection/ViewComponents/UserSignedUpSubjectsViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SubjectSelection.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SubjectSelection.ViewComponents
{
    public class UserSignedUpSubjectsViewComponent : ViewComponent
    {
        private readonly SubjectSelectionDbContext _context;

        private readonly UserManager<User> _userManager;

        public UserSignedUpSubjectsViewComponent(UserManager<User> userManager, SubjectSelectionDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public IViewComponentResult Invoke()
        {
            var user = this.GetCurrentUserAsync().Result;
            //_context.UserGroups.Where(ug => ug.UserId == user.Id).Select(ug => ug.GroupId)
            var currentUserDb = _context.User.Include(u => u.UserGroups).SingleOrDefault(u => u.Id == user.Id);
            var groupIds = currentUserDb.UserGroups.Select(ug => ug.GroupId);
            var subjectsSignedUpTo = _context.Groups.Include(g => g.Subject).Where(g => groupIds.Contains(g.GroupId)).Select(g => g.Subject);

            //var subjectsSignedUpTo = user.UserGroups?.Select(ug => ug.Group)?.Select(g => g.Subject);

            if (subjectsSignedUpTo == null)
                return View(new List<Subject>());

            return View(subjectsSignedUpTo);
        }
    }
}

SubjectSelection/Views/Home/About.cshtml
 @{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SubjectSelection/Views/Home/CreateSubjectList.cshtml
@model SubjectSelection.Models.SubjectList

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>SubjectList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class ="form-control" asp-items="ViewBag.OwnerId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SubjectSelection/Views/Home/Delete.cshtml
@model SubjectSelection.Models.SubjectList

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubjectList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Owner Card Id
            @*@Html.DisplayNameFor(model => model.Owner)*@
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Owner.StudentCardId)
        </dd>
    </dl>
    
    <form asp-action="DeleteSubjectList">
        <input type="hidden" asp-for="SubjectListId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SubjectSelection/Views/Home/Edit.cshtml
@model SubjectSelection.Models.SubjectList

<h4>SubjectList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SubjectListId" />
            <input type="hidden" asp-for="OwnerId" />

            @*<div class="form-group">
            <label asp-for="OwnerId" class="control-label"></label>
            <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
            <span asp-validation-for="OwnerId" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" asp-route-subjectListId="@Model.SubjectListId" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SubjectSelection/Views/Home/Index.cshtml
@model ICollection<SubjectSelection.Models.SubjectList>


@{
    ViewData["Title"] = "Home Page";
    var search = ViewBag.search;
    var currentUserId = ViewBag.currentUserId;

}

<style type="text/css">
    a:hover {
        cursor: pointer;
    }
</style>

<form asp-action="SearchSubjectLists" method="get">
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label for="subjectListName">Search subject list</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-11">
                <input type="text" class="form-control" id="subjectListName" placeholder="Enter name" name="subjectListName" />
            </div>
            <div class="col-md-1">
                @*<button asp-action="SearchSubjectLists" asp-route-subjectListName="" class="btn btn-primary">Search</button>*@
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </div>
</form>

<div class="@(search?"col-md-12":"col-md-6")">
    <div class="row">
        <div class="col-md-12">
            User created subject lists:
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Owner card Id
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Owner.StudentCardId)
                            </td>
                            <td class="@(currentUserId == item.OwnerId ? string.Empty : "hidden")">
                                <a asp-controller="Subjects" asp-action="Index" asp-route-parentListId="@item.SubjectListId">Details</a> |
                                <a asp-action="Edit" asp-route-parentListId="@item.SubjectListId">Edit</a> |
                                <a asp-action="Delete" asp-route-subjectListId="@item.SubjectListId">Delete</a>
                            </td>
                            <td class="@(currentUserId != item.OwnerId ? string.Empty : "hidden")">
                                <a asp-controller="Subjects" asp-action="Index" asp-route-parentListId="@item.SubjectListId">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    @if (!search)
    {
        <div class="row">
            <div class="col-md-12">
                <form asp-action="CreateSubjectList">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="subjectListName">SubjectList Name</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-10">
                                <input type="text" class="form-control" id="subjectListName" placeholder="Enter name" name="subjectListName" />
                            </div>
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    }
</div>
@if (!search)
{
    @:Subjects user is signed up to:
    <div class="col-md-6">
        @await Component.InvokeAsync("UserSignedUpSubjects")
    </div>
}



@*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">

    </script>*@

<script src="bootstrap/js/bootstrap.min.js"></script>
@*<script type="text/javascript">

        $(document).ready(function () {
            $(".btnShowModal").click(function () {
                $("#loginModal").modal('show');
            });

            $(".btnHideModal").click(function () {
                $("#loginModal").modal('hide');
            });
        });
    </script>*@

@*<div class="modal fade" tabindex="-1" id="loginModal"
         data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        ×
                    </button>
                    <h4 class="modal-title">Delete</h4>
                </div>
                <div class="modal-body">
                    <form asp-action="DeleteSubjectList">
                        <div class="form-group">
                            Are you sure you want to delete this Subject List?
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary button button4">Yes</button>
                    <button type="button" id="btnHideModal" class="btn btn-primary button button4">
                        Cancel
                    </button>
                </div>
            </div>
        </div>
    </div>*@